### ISSUE TITLE
Not asked for MFA at all

### ISSUE THREAD

**Issue by ghost** [oktadeveloper/okta-aws-cli-assume-role#134] opened 2018-07-02 14:35 UTC
Hi after reading about some issues I still don't have 100% clear if what I'm trying to do is possible or not. 

As far as I understood okta-aws-cli-assume-role is capable of doing the MFA so Okta in this case as my IdP can send me a push notofication to my phone via "okta verify" right?. 
I've been reading all the comments and issues, and all of them are asked for MFA, but I'm not even asked...And of course it's configured and working in the whole company for all the apps. 

So,  what Im missing? Is there some special param/variable to set to enable the MFA? 

If I disable in Okta the MFA in some aws environment, for my user, it works: 
<img width="782" alt="captura de pantalla 2018-07-02 a las 15 01 38" src="https://user-images.githubusercontent.com/29625543/42170925-2de8d00c-7e18-11e8-8907-4c957e84a4e3.png">

But if I enable it again: 

<img width="721" alt="captura de pantalla 2018-07-02 a las 16 18 07" src="https://user-images.githubusercontent.com/29625543/42169690-b8980d2a-7e14-11e8-9cd9-1c60ced344a9.png">

Here's my cfg: 
`
OKTA_ORG=XXXXXX.okta-emea.com

OKTA_AWS_APP_URL=https://XXXXX.okta-emea.com/home/amazon_aws/aaaaaabbbbcccccc/666

OKTA_USERNAME=user@blah.com

OKTA_PASSWORD=*************

OKTA_AWS_ROLE_TO_ASSUME=arn:aws:iam::07001010010:role/pro-okta-admin

#OKTA_STS_DURATION=28800

OKTA_BROWSER_AUTH=false
`

Thank you!

**Comment by poljane** [comment] 2018-07-02 14:38
ok I see, in 

issue: https://github.com/oktadeveloper/okta-aws-cli-assume-role/issues/106

but what about asking? I'm not promted for anything related to MFA it just works or fail and Okta logs says "Success".

**Comment by AlainODea** [comment] 2018-07-05 20:37
The problem is that app-level MFA is post-authentication when it hands off to the app. The need to prompt is not visible in the API or the error response. There's not really any present way to distinguish between a generic failure and a failure due to the need for app-level MFA.

Please go ahead and close this issue. No fix is possible without changes to the Okta APIs.

**Comment by AlainODea** [comment] 2018-07-25 01:17
@mraible can you close this one. The user deleted their GitHub account and it requires Okta Platform service-side changes to fix.

**Closed** 2018-07-25 03:57 UTC
