### ISSUE TITLE
Web login takes me to management console

### ISSUE THREAD

**Issue by gstathisfs** [oktadeveloper/okta-aws-cli-assume-role#320] opened 2019-06-25 20:14 UTC
**Describe the bug**
When I login to okta via the web browser the tool loads the aws management console and hangs there. 

**To Reproduce**
1. Download tool
2. run okta-aws test sts get-caller-identity
3. login 
4. page loads console and hangs

**Expected behavior**
The browser should close and spit out credentials 

**Additional context**
This is on macOSX Mojave
The tool does work some times but it seems random as to when it wont hang on the console

**Comment by jeremyplichtafc** [comment] 2019-06-26 00:45
seems like duplicate of https://github.com/oktadeveloper/okta-aws-cli-assume-role/issues/317 - fix is on master, waiting for new release of the project for it to be included. You can follow instructions in that issue to build locally though and it should work for you.

**Comment by gstathisfs** [comment] 2019-06-26 12:53
I have taken the resulting snapshot jar from the locally built project however it still locks me in to the aws console when I replace the jar in ~/.okta

**Comment by gstathisfs** [comment] 2019-06-26 15:29
Downgrading to version 1.0.10 has made the tool work thank you

**Comment by jeremyplichtafc** [comment] 2019-06-26 16:00
There is a symlink of the jar without a version number in `~/.okta` that needs to point to the new jar that you built in order for the change to be picked up

**Comment by gstathisfs** [comment] 2019-06-26 16:22
I have updated the symlink of okta-aws-cli.jar to point to the new 2.0.3 snapshot jar that I have built but it still hangs on the management console screen

**Comment by nema-sigsci** [comment] 2019-06-27 05:21
I also rebuilt the 2.0.3 snapshot jar and copied it over the 2.0.2.jar version.

Now the pop up will close before i can choose a role and the cli will ask me to select a role. Once I input the number of the role I want, it fails by telling me `Unable to locate credentials. You can configure credentials by running "aws configure".`

I'm on macOS Mojave 10.14.5.

**Comment by gstathisfs** [comment] 2019-06-27 12:50
Weird even if I just copy the built 2.03 jar over the 2.0.2 jar it still hangs on the management console. The only thing that has worked for me is copying over the cli jar with the old 1.0.10 jar

**Comment by nema-sigsci** [comment] 2019-06-27 14:49
@gstathisfs 

I did the following and was able to get it to work. 
1. Download the 2.0.0.jar
2. remove the symlink for `okta-aws-cli.jar`
``` rm okta-aws-cli.jar```
3. Move the 2.0.0.jar into the .okta folder and then symlink that version
```ln -s okta-aws-cli-2.0.0.jar okta-aws-cli.jar```

**Comment by jeremyplichtafc** [comment] 2019-08-22 03:14
There were a few different issues here. I think you were running into the issue where if you only had one AWS role to choose from it would log in and hang (https://github.com/oktadeveloper/okta-aws-cli-assume-role/issues/328) this was fixed in latest release 2.0.4

**Comment by jeremyplichtafc** [comment] 2019-08-22 03:31
closing this out as I believe it is fixed. let me know if you still see it with latest release v2.0.4

**Closed by jeremyplichtafc** 2019-08-22 03:31 UTC
